# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth/v1/auth.proto\x12\x07\x61uth.v1\x1a\x16\x63ommon/v1/common.proto\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"c\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12 \n\x07user_id\x18\x02 \x01(\x0b\x32\x0f.common.v1.Uuid\x12\x1f\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x10.common.v1.Error\"@\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"F\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\r2\x8a\x01\n\x0b\x41uthService\x12\x38\n\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x00\x12\x41\n\x08Register\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\"\x00\x42\x1eZ\x1cgateway/proto/auth/v1;authv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034gateway/proto/auth/v1;authv1'
  _globals['_LOGINREQUEST']._serialized_start=55
  _globals['_LOGINREQUEST']._serialized_end=102
  _globals['_LOGINRESPONSE']._serialized_start=104
  _globals['_LOGINRESPONSE']._serialized_end=203
  _globals['_REGISTERREQUEST']._serialized_start=205
  _globals['_REGISTERREQUEST']._serialized_end=269
  _globals['_REGISTERRESPONSE']._serialized_start=271
  _globals['_REGISTERRESPONSE']._serialized_end=341
  _globals['_AUTHSERVICE']._serialized_start=344
  _globals['_AUTHSERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
